---
deployment:
 tasks:
  - export DEPLOYPATH=/home/n1607723/oktan-itb-api/
  - /bin/rm -Rf $DEPLOYPATH
  - /bin/mkdir $DEPLOYPATH
  - /bin/cp server.js $DEPLOYPATH
  - /bin/cp package.json $DEPLOYPATH
  - /bin/cp package-lock.json $DEPLOYPATH
  - /bin/cp -R src/ $DEPLOYPATH
  - /bin/cp -R public/ $DEPLOYPATH
  - /bin/mkdir $DEPLOYPATH/tmp
  - /bin/touch $DEPLOYPATH/tmp/restart.txt
